In [1]:
import pandas as pd
import numpy as np

import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing

from sklearn.datasets import load_boston

In [2]:
df = load_boston()

In [3]:
type(df)

sklearn.utils.Bunch

In [4]:
df.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [5]:
boston = pd.DataFrame(df.data)
boston.head(20)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27
12,0.09378,12.5,7.87,0.0,0.524,5.889,39.0,5.4509,5.0,311.0,15.2,390.50,15.71
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26
15,0.62739,0.0,8.14,0.0,0.538,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47
16,1.05393,0.0,8.14,0.0,0.538,5.935,29.3,4.4986,4.0,307.0,21.0,386.85,6.58
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69
19,0.72580,0.0,8.14,0.0,0.538,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28

In [6]:
boston.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

In [7]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       506 non-null    float64
 1   1       506 non-null    float64
 2   2       506 non-null    float64
 3   3       506 non-null    float64
 4   4       506 non-null    float64
 5   5       506 non-null    float64
 6   6       506 non-null    float64
 7   7       506 non-null    float64
 8   8       506 non-null    float64
 9   9       506 non-null    float64
 10  10      506 non-null    float64
 11  11      506 non-null    float64
 12  12      506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB

In [8]:
boston.columns = df.feature_names
boston.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [9]:
X = boston
y = df.target
print( "shape of X = ", X.shape, " shape of y = ", y.shape )

shape of X =  (506, 13)  shape of y =  (506,)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, random_state=101)

In [11]:
scaler = preprocessing.StandardScaler( )
X_train = scaler.fit_transform( X_train )
X_train

array([[ 1.35931755, -0.48538476,  0.97581105, ...,  0.79324166,
         0.17394382,  2.56628796],
       [-0.12215088, -0.48538476,  1.19198907, ..., -1.75808104,
        -2.95621038,  0.46640441],
       [-0.4208706 ,  0.52910508, -0.84417416, ..., -0.78393964,
         0.43797386, -0.65169658],
       ...,
       [-0.4232884 , -0.48538476, -0.90990397, ...,  0.79324166,
         0.41496207, -0.34280487],
       [-0.4124382 ,  0.11847824, -0.51844647, ..., -1.52614261,
         0.43797386,  0.0501982 ],
       [-0.41717036,  2.41315762, -1.42113577, ..., -0.08812436,
         0.15038151, -1.07805415]])

In [12]:
y_train

array([10.2, 13.1, 23.4, 22.1, 34.9, 20.5, 24.5, 29.8, 25. , 25.1, 22. ,
       46.7, 20.4, 13.4, 42.3, 37.2, 18.4, 24.8, 19.9, 20.4, 28.1, 20.7,
       29.1, 17.5, 23.2, 50. , 50. , 21.2, 22.5, 20.1, 17.2, 17.8, 25. ,
       19.4, 25. , 50. , 26.6, 24.8, 20.3, 18.9, 29.9, 12.6, 11.8, 22.6,
       35.4, 43.1, 23.1, 17.9, 14.5, 26.6, 14.1, 28.6, 24.6, 23.3, 21.1,
       20.6, 50. , 22.3, 43.5, 21.5, 14.9, 19.3, 19.4, 24.2, 33.1, 17.8,
       18.8, 27.5, 22.6, 15. , 20.1, 21.2, 27. , 18.8, 23.8, 24.4, 36.2,
       20.3, 14.3, 19.3, 18.7, 31.2, 16.7, 16.1, 15.6, 27.5, 13.9, 23.2,
       18.6, 33.4, 19.8, 50. , 20. , 23.1,  7. , 21. ,  7.2, 22.8, 24.3,
       21.7, 23.7, 19.1, 17.1, 13.1, 24.5, 24.1,  7. , 24.4, 23.2,  9.7,
       17.3, 25.2, 50. , 35.1, 23.4, 18.3, 13.6, 19.3, 16.7, 16.2, 21.6,
       50. , 19.5, 18.1,  8.7, 22.9, 29.8, 14.9, 30.1, 19.4, 20.5, 33.8,
       17.2, 13.6, 37.9, 17.5, 12.7, 23.9,  5.6, 26.6, 26.4, 23.3, 24.6,
       19.8, 22.2, 23.1, 18.3, 18.9, 21. , 13.5, 21.6, 23.1, 13.3, 26.5,
       21.5, 11.9, 12.3, 22. , 17.5, 19. , 13.9, 20.2, 15.1, 14.1, 21.8,
       15.2, 21.7, 24.4,  7.4, 20.6, 10.2,  7.2, 15.2, 25.3, 22.9, 22.2,
       23.6, 19.7, 28. , 36. , 23.1, 31.1, 13.8, 18.9, 41.7, 19.4, 19.1,
       16.6, 19.6, 29.6, 13.8, 20.5, 21.4, 37. , 20.1, 23.9, 11.8, 23.9,
       13.8, 16.8, 21.1, 28.2, 15.6, 16. , 33.3, 17.4, 20.3, 14.3, 29. ,
       22. , 18.2, 21.4, 14.2, 50. , 27.9, 38.7, 22. , 23. , 21.8, 20.3,
       22.9, 13.3,  8.5,  8.1, 39.8, 45.4, 42.8, 25. ,  7.5, 25. , 13.4,
       26.4, 10.2, 22.7, 20.8, 24.8, 11. , 28.7, 28.4, 19.1, 14.8, 20.8,
       34.9, 17.8, 20.6, 21.9, 24. , 14.5, 19.6, 15.4, 22. ,  9.5, 19.6,
       20. , 20.6, 37.6, 22.5, 50. , 17.6, 21.7, 21.7, 21.9, 20.6, 13.4,
       48.8, 22. ,  8.3, 30.3, 24.4, 18.2, 33.1, 18.7, 23.7, 33.4, 18.4,
       18.7, 16.1, 13.1, 22.9, 16.4, 23.3, 10.8, 10.5, 23.6, 17.1, 23.7,
       31.5, 16.6, 22.6, 21.4, 46. , 13.1, 16.5, 20. , 17.2, 33.2, 18.4,
       15. , 12.7,  8.4, 19.9, 30.5, 10.4, 19.7, 15.3, 30.1, 48.5, 24.5,
       35.2, 14. , 20.8, 21.2, 24. , 24.8,  6.3, 13. , 22.2, 12.1, 15.2,
       22.6, 23.7, 21.7, 19.3, 10.5,  9.6, 19.1, 27.1, 21. , 32.2, 33.2,
       22.7, 22.2, 36.5, 23.3, 13.5, 19.5,  8.8, 23.9, 20.4, 30.1, 20. ,
       12.7, 15.7, 32. , 26.2, 19.3, 21.2,  8.8, 19.6, 14.6, 16.3, 50. ,
       17.4, 22.8, 19. , 19.4, 21.2, 12. , 12.5, 28.7, 21.7, 36.4, 26.7,
       17.8, 18.5, 11.7, 22.4, 23. , 34.9, 17.7, 13.8, 23.1, 21.4, 22.2,
       25. , 23. , 18.5, 18.9, 24.1])

In [15]:
feature_columns = df.feature_names
regressor = tf.estimator.DNNRegressor(feature_columns=None,hidden_units=[10, 20, 10])

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\MAHMUD~1\AppData\Local\Temp\tmpjxgoxrii
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\MAHMUD~1\\AppData\\Local\\Temp\\tmpjxgoxrii', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

In [ ]:
regressor.train(X_train, y_train, steps=5000)